// <auto-generated />
using System;
using JuiceTelegramBot.Core.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JuiceTelegramBot.Core.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20181105032936_LinkBetweenJuiceAndOrder")]
    partial class LinkBetweenJuiceAndOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JuiceTelegramBot.Core.Model.JuiceDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCustom");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Juices");
                });

            modelBuilder.Entity("JuiceTelegramBot.Core.Model.OrderDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JuiceId");

                    b.Property<DateTime>("OrderDateTime");

                    b.HasKey("Id");

                    b.HasIndex("JuiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JuiceTelegramBot.Core.Model.OrderDb", b =>
                {
                    b.HasOne("JuiceTelegramBot.Core.Model.JuiceDb", "Juice")
                        .WithMany()
                        .HasForeignKey("JuiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
